/* InfoTech.io | acesso administrativo direto: contas, empresas e arquivamento seguro. */
(() => {
 'use strict';
 const $=id=>document.getElementById(id);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let client,busy=false,companyStatuses={};
 const message=(text,error=false)=>{$('feedback').innerHTML=`<div class="note ${error?'error':'success'}">${esc(text)}</div>`};
 const css=document.createElement('style');
 css.textContent=`#companyForm,#staffForm,#countInvites{display:none!important}.it-access{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-bottom:24px}.it-access .card{min-width:0}.it-password{position:relative}.it-access .card label{margin-bottom:2px}.it-access .card form{margin-top:12px}.it-inline{display:flex;gap:10px;align-items:center}.it-inline input{flex:1}.it-archive{background:#391b28!important;color:#ffd8e0!important;border-color:#9b5268!important}.it-status{text-transform:capitalize}.it-danger{margin-top:8px;font-size:12px;color:#c9d6ea}@media(max-width:760px){.it-access{grid-template-columns:1fr}.it-inline{flex-wrap:wrap}.it-inline input{width:100%}.it-access .card{padding:16px}}`;
 document.head.appendChild(css);
 async function verified(){const auth=await client.auth.getUser();if(auth.error||!auth.data?.user)throw Error('Faça login como administrador.');const {data,error}=await client.rpc('detailnow_is_platform_admin');if(error||data!==true)throw Error('Esta conta não possui acesso administrativo.');}
 async function rpc(name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
 async function provision(email,password){const {data,error}=await client.functions.invoke('detailnow-admin-create-account',{body:{email,password}});if(error)throw Error(error?.context?.status===403?'Sem permissão para criar usuários.':(error.message||'Falha ao criar usuário.'));if(data?.error)throw Error(data.error);return data}
 async function overview(){const data=await rpc('detailnow_admin_overview');companyStatuses=Object.fromEntries((data.companies||[]).map(c=>[c.id,c.status]));addArchiveButtons();const selected=$('itStaffCompany')?.value||'';const list=$('itStaffCompany');if(list){list.innerHTML=(data.companies||[]).filter(c=>c.status==='active').map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');if([...list.options].some(o=>o.value===selected))list.value=selected;}return data}
 async function perform(fn){if(busy)return;busy=true;document.querySelectorAll('[data-it-submit]').forEach(b=>b.disabled=true);try{await verified();await fn();await overview();}catch(err){message(err?.message||'Não foi possível concluir.',true)}finally{busy=false;document.querySelectorAll('[data-it-submit]').forEach(b=>b.disabled=false)}}
 const newMarkup=`<section class="it-access" id="itAccess"><article class="card"><div class="eyebrow">CADASTRO DE EMPRESAS</div><h3>Nova empresa e proprietário</h3><form id="itCompanyForm"><label>Nome do estabelecimento<input name="name" required minlength="2" maxlength="90" placeholder="Ex.: Oliveira Estética Automotiva"></label><label>Gmail do CEO<input name="email" type="email" autocomplete="off" required placeholder="proprietario@gmail.com"></label><label>Senha inicial<input name="password" type="password" autocomplete="new-password" minlength="10" maxlength="128" required placeholder="Mínimo de 10 caracteres"></label><button data-it-submit class="btn btn-primary" type="submit">Criar empresa e conta</button></form><div class="it-danger">O proprietário confirma o e-mail antes de acessar. Para contas já existentes no Supabase, a senha anterior é preservada.</div></article><article class="card"><div class="eyebrow">EQUIPE</div><h3>Cadastrar funcionário</h3><form id="itStaffForm"><label>Estabelecimento<select id="itStaffCompany" name="workspace" required></select></label><label>Gmail do funcionário<input name="email" type="email" autocomplete="off" required placeholder="funcionario@gmail.com"></label><label>Senha inicial<input name="password" type="password" autocomplete="new-password" minlength="10" maxlength="128" required placeholder="Mínimo de 10 caracteres"></label><button data-it-submit class="btn btn-primary" type="submit">Criar funcionário</button></form><div class="it-danger">O funcionário usará os preços definidos pelo proprietário.</div></article></section>`;
 function install(){const app=$('adminApp');if(!app||$('itAccess'))return;const original=app.querySelector('section.section.layout');if(original){original.insertAdjacentHTML('beforebegin',newMarkup);original.classList.add('hidden');}const invitations=$('companyInvites')?.closest('section.section.layout');if(invitations)invitations.classList.add('hidden');const inviteMetric=$('countInvites')?.closest('.metric');if(inviteMetric)inviteMetric.classList.add('hidden');
  $('itCompanyForm')?.addEventListener('submit',ev=>{ev.preventDefault();const f=ev.target;if(!f.reportValidity())return;perform(async()=>{const name=f.elements.name.value.trim(),email=f.elements.email.value.trim().toLowerCase(),password=f.elements.password.value;const account=await provision(email,password);await rpc('detailnow_admin_provision_company',{p_name:name,p_email:email});f.reset();message(account.confirmationSent?'Empresa e proprietário criados. Verifique a caixa de entrada para confirmar o Gmail.':account.created?'Empresa criada. O e-mail de confirmação não pôde ser enviado automaticamente; verifique o SMTP do Supabase.':'Empresa vinculada à conta existente.');});});
  $('itStaffForm')?.addEventListener('submit',ev=>{ev.preventDefault();const f=ev.target;if(!f.reportValidity())return;perform(async()=>{const email=f.elements.email.value.trim().toLowerCase(),password=f.elements.password.value,workspace=f.elements.workspace.value;if(!workspace)throw Error('Selecione um estabelecimento.');const account=await provision(email,password);await rpc('detailnow_admin_provision_staff',{p_workspace:workspace,p_email:email});f.elements.email.value='';f.elements.password.value='';message(account.confirmationSent?'Funcionário cadastrado. Confirme o Gmail para ativar o acesso.':account.created?'Funcionário criado. Verifique o envio do e-mail de confirmação no Supabase.':'Funcionário cadastrado com a conta existente.');});});
 }
 const patched=new WeakSet();
 function addArchiveButtons(){const rows=$('companyRows');if(!rows)return;for(const row of rows.querySelectorAll('tr')){if(patched.has(row))continue;const buttons=row.querySelectorAll('button[data-action="status"]');if(!buttons.length)continue;patched.add(row);const status=buttons[0];const id=status.dataset.id;const company=row.querySelector('td strong')?.textContent||'';const archived=companyStatuses[id]==='deleted';if(archived){const badge=row.querySelector('.badge');if(badge)badge.textContent='Excluída';status.textContent='Recuperar';continue;}const btn=document.createElement('button');btn.type='button';btn.className='btn btn-sm it-archive';btn.textContent='Excluir';btn.dataset.itAction='archive';btn.dataset.workspace=id;btn.dataset.company=company;status.parentElement.append(btn)}}
 document.addEventListener('DOMContentLoaded',async()=>{install();client=window.supabase?.createClient('https://yncspxfsvlqdnodlsosb.supabase.co','sb_publishable_jALAHHuvrV5oxj2mugWTCQ_stD_vFyN',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});if(!client)return;
  const rows=$('companyRows');if(rows){new MutationObserver(addArchiveButtons).observe(rows,{childList:true});addArchiveButtons()}
  try{await verified();await overview()}catch(_){ /* Painel original bloqueia contas sem autorização. */ }
  $('loginForm')?.addEventListener('submit',()=>setTimeout(()=>overview().catch(()=>{}),1200));
 });
 document.addEventListener('click',ev=>{const btn=ev.target.closest('[data-it-action="archive"]');if(!btn)return;ev.preventDefault();ev.stopImmediatePropagation();const name=btn.dataset.company,id=btn.dataset.workspace;
  const entered=window.prompt(`Exclusão segura: digite exatamente o nome da empresa para arquivar e bloquear o acesso:\n\n${name}`);
  if(entered===null)return;if(entered.trim()!==name)return message('Nome diferente. A empresa não foi excluída.',true);
  if(!window.confirm(`Confirmar exclusão de ${name}? O acesso será bloqueado e os dados ficarão preservados para eventual recuperação.`))return;
  perform(async()=>{await rpc('detailnow_admin_archive_company',{p_workspace:id,p_confirm_name:name});message('Empresa excluída do acesso. Dados preservados em arquivo.');location.reload()})
 },true);
})();